runtime: nodejs8

instance_class: F2

handlers:
- url: /public
  static_dir: /output/public
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

service: nodejs

env_variables:
  GCLOUD_TRACE_NEW_CONTEXT: 1
  APP_ENGINE_ENVIRONMENT: appengine
